### ISSUE TITLE
How do I share a user-created theme?

### ISSUE THREAD

**Issue by sn3ksoftware** [ColdGrub1384/Pyto#102]
By looking at the source code, it seems that the theme is Base64-encoded. Is there a way to share/install themes using this string?

**Comment by cclauss** [comment]
See the function in https://docs.python.org/3.8/library/base64.html

**Comment by ColdGrub1384** [comment]
That's currently not supported by the app but I just wrote a script for that.

https://gist.github.com/ColdGrub1384/929f59fd3197bc8de360cb781f8a70d1

**Comment by sn3ksoftware** [comment]
Thank you! Maybe someday there will be a option to share/import themes in the settings.
