### ISSUE TITLE
pip install error , GPy package

### ISSUE THREAD

**Issue by acclaude** [ColdGrub1384/Pyto#106]
I'm trying to install GPy package with pip.
It seems that a configuration file could not be saved.
Thx for your help
Claude

![pip_error_module_gpy](https://user-images.githubusercontent.com/57643054/68625780-424dd480-04da-11ea-9413-63a1b9bb1202.jpeg)

**Comment by acclaude** [comment]
I have to add site-packages in  "Current-directory" and it works !!!

**Comment by cclauss** [comment]
Can this issue be closed?

**Comment by acclaude** [comment]
Yes

**Comment by cclauss** [comment]
Please hit the `Close issue` button below.
