### ISSUE TITLE
Input field on iPad?

### ISSUE THREAD

**Issue by ifuchs** [ColdGrub1384/Pyto#113]
Can someone please tell me the purpose of the input field on the bottom right (on the iPad)? It accepts input but I don’t know where it is going or what it is doing.

**Comment by cclauss** [comment]
https://docs.python.org/3/tutorial/interpreter.html

**Comment by ColdGrub1384** [comment]
The input is sent to the currently running script or REPL. If a script doesn't asks for input, writing on the input field does nothing

**Comment by ifuchs** [comment]
Thanks, I guess that should have been obvious but I somehow assumed that the input field would only appear when the program was requesting input.
