### ISSUE TITLE
Colorized output is lost when switching apps

### ISSUE THREAD

**Issue by fprimex** [ColdGrub1384/Pyto#115]
Thanks for the great app! The new colorized output works great, but gets lost when switching away from & back to Pyto. The script I tested with is here (from [reddit](https://gist.github.com/isametry/e294272da2461a4dfe178c737b0df1a0)):

https://gist.github.com/isametry/e294272da2461a4dfe178c737b0df1a0

And here's a screen recording of the issue:

https://share.icloud.com/photos/0hNAVWC8xnL4jIP1ASMoDYTIg

**Comment by ColdGrub1384** [comment]
I thought I fixed the issue, but no :|
