### ISSUE TITLE
Hardware keyboard autocompletion not working

### ISSUE THREAD

**Issue by marcosgeorgopoulos** [ColdGrub1384/Pyto#121]
Hi,

I got the impression from [https://github.com/ColdGrub1384/Pyto/issues/47](url) that tab auto completion should work on a hardware keyboard. I have the apple smart case keyboard for the MacBook Pro and it does not work for me.

For example I type
`requests.g`

And at the bottom of the screen I have one option ‘get’

If I hit tab on my keyboard it just inserts a tab.

**Comment by marcosgeorgopoulos** [comment]
Oh ok thank you. I couldn’t find it documented anywhere

**Comment by cclauss** [comment]
Can you please close this issue?
