### ISSUE TITLE
Having trouble figuring out pip on ios

### ISSUE THREAD

**Issue by cclauss** [ColdGrub1384/Pyto#13]
When I try to use pip to install a PyPI module, I get the message
> __pip rubicon.objc.api.ObjCInstance Pyto.Python has no attribute name__

Which repeats itself over and over again until I hit the X.  Am I doing something wrong?

**Comment by ColdGrub1384** [comment]
No, that’s a bug. The installer should work, but the message is shown.

**Comment by ColdGrub1384** [comment]
Fixed on 12fdeed7e8fd2ad032bc5154ab2fca0d7b083151. Thank you so much for reporting the bug. I'm publishing the update and it will available soon.

**Comment by cclauss** [comment]
Fixed in 12fdeed.
