### ISSUE TITLE
deprecated warnings

### ISSUE THREAD

**Issue by 7points** [ColdGrub1384/Pyto#144]
Every time a script is loaded and executed during a pyto session, deprecated warnings are issued with reference to matplotlib 3.1, although matplotlib was not imported.

**Comment by ColdGrub1384** [comment]
I think that has something to do with the `mpl-data` folder using deprecated features. If you have nothing important there, try deleting `On My iPad / iPhone > Pyto > mpl-data`

**Comment by 7points** [comment]
That's it, thank you!
