### ISSUE TITLE
Cannot install pyTDS

### ISSUE THREAD

**Issue by ifuchs** [ColdGrub1384/Pyto#149]
Trying to use pip to install pyTDS and I get:

Error: Version not found: pyTDS[('==', '1.8')]

**Comment by ifuchs** [comment]
Problem solved. PyTDS and sqlalchemy_pytds installed and working.

**Comment by cclauss** [comment]
Please close this issue?

**Comment by ifuchs** [comment]
In spite of the error message, it was installed.
