### ISSUE TITLE
Crash when starting a script in succession

### ISSUE THREAD

**Issue by 7points** [ColdGrub1384/Pyto#153]
The last program version from Testflight --> 11.6.1 (1) produces a crash without any error message if the script was often started in succession (often after 10 starts).
  For example following simple script:
  print ('hello')

  The error occurs on iPad Pro and iPhone.

 The issue is not reproducible in the following test flight versions:
  --> 11.5 (4) and --> 11.6 (1)

**Comment by ColdGrub1384** [comment]
Thanks. I just fixed that
