### ISSUE TITLE
Help modules crashes Pyto

### ISSUE THREAD

**Issue by ifuchs** [ColdGrub1384/Pyto#155]
Type
Help()

Modules
Error msgs followed by return to home screen.

**Comment by ColdGrub1384** [comment]
I'm not able to reproduce the crash. Could you take a screenshot of error messages shown before crashing please?

**Comment by ifuchs** [comment]
That’s a little difficult since it crashes to the home screen. I did a video and grabbed the frame before it crashes. If you want the entire video, I can upload it somewhere (it is 30MB).

**Comment by ifuchs** [comment]
@ColdGrub1384  Here is the screen image: https://imgur.com/hFLtL4O

**Comment by ColdGrub1384** [comment]
Ah I see, it's after typing `modules`. I now have the crash too, thank you. I'll try to fix it.
