### ISSUE TITLE
Pyto crash because of os LIB

### ISSUE THREAD

**Issue by tioannidis** [ColdGrub1384/Pyto#159]
Hello,

if I import the os lib and type in the next line os. Pyto crashes  without message after the typing of dot „.“

Example:
`import os`
`os.`

I have the Ipad 6.Generation with IOS 13.4

Could you please help?
thx

**Comment by ColdGrub1384** [comment]
Hi. Sorry for the bug. I fixed it and I released a new update. It should be available on the App Store in a few moments.

**Comment by tioannidis** [comment]
@ColdGrub1384 
![D4E01CBD-6E49-4570-B42A-0FD6089B33DC](https://user-images.githubusercontent.com/1592909/79697808-274f6f80-8285-11ea-8b5f-f3551f78283f.jpeg)

thx for the quick fix
