### ISSUE TITLE
Question: File Permissions

### ISSUE THREAD

**Issue by tioannidis** [ColdGrub1384/Pyto#161]
Hi,
I am newby on ios so I think this is not a bug in Pyto.
My question is how I can get read/write permissions in the ios filesystem to handle with files. It would be enough if I could read and write in my project directory. My work directory is in the workingCopy App.

```ruby
import os
import sys

print(sys.path)

print(os.access("/private/var/mobile/Containers/Shared/AppGroup/C4EF0D1D-DED3-40E1-A322-F21A53026D70/File Provider Storage/Repositories/python/", os.R_OK))

print(os.access("Documents", os.R_OK))

```

```ruby

['Pyto.app', '/var/mobile/Containers/Data/Application/CD3CD08D-DF09-49AB-B590-1B9A92B57AF0/Library/python38', 'Pyto.app/Lib', 'Pyto.app/site-packages', '/var/containers/Bundle/Application/9F71DB53-FFFF-4544-900F-AE987252B505/Pyto.app/Frameworks/Python.framework/python38.zip', '/var/containers/Bundle/Application/9F71DB53-FFFF-4544-900F-AE987252B505/Pyto.app/Frameworks/Python.framework/lib/python38.zip', '/var/containers/Bundle/Application/9F71DB53-FFFF-4544-900F-AE987252B505/Pyto.app/Frameworks/Python.framework/lib/python3.8/~/Documents/site-packages', 'Documents', '/private/var/mobile/Containers/Shared/AppGroup/C4EF0D1D-DED3-40E1-A322-F21A53026D70/File Provider Storage/Repositories/python', 'Documents/site-packages', '/var/containers/Bundle/Application/9F71DB53-FFFF-4544-900F-AE987252B505/Pyto.app/Frameworks/Python.framework/lib/python3.8/lib-dynload']

False

False

```

Could someone help me please or give me a exaple code?

Best Regards,
Theo

**Comment by ColdGrub1384** [comment]
Hi. The problem is that iOS doesn’t let apps access external folders without manually picking them. To grant access to the directory, press the menu icon on the main screen, go to Settings and then “Accessible Folders”. Then you can pick the directory and Pyto will have access to it.

**Comment by tioannidis** [comment]
Hi, yes I granted the access
![544A0C28-C866-43C2-A23A-2A71C48DA630](https://user-images.githubusercontent.com/1592909/79768412-0b060e00-832b-11ea-9f63-f3c6c3867c12.jpeg)

and Pyto App can create new files.py in this directory, but not my pyto script so I have no idea whats wrong in my case :-( :
![843BC0AE-16CB-4411-8603-43D0848E8362](https://user-images.githubusercontent.com/1592909/79768677-6506d380-832b-11ea-83d6-f51a8c42e1ba.jpeg)

Have you an idea or code example with r/w access in the py code?

**Comment by ColdGrub1384** [comment]
@tioannidis Are you sure you granted access from Pyto settings? Or just in the file browser? The file browser can create files in external directories because it's like another process (if the app freezes, the file browser doesn't). Then the app can only access files selected by the user.
![IMG_43CD44CFAB66-1](https://user-images.githubusercontent.com/19255527/79872190-75629100-83b3-11ea-8e28-f5f87bb7823b.jpeg)

**Comment by tioannidis** [comment]
ups...I granted just in the file browser... sorry :-)
now it works (with the full path)

many thx for your support
 
![2A4B691F-4F50-4814-A07D-1218E267F5C6](https://user-images.githubusercontent.com/1592909/79877255-503e4480-83ec-11ea-8412-faf5cb146ead.jpeg)

**Comment by ColdGrub1384** [comment]
Great!
