### ISSUE TITLE
Pyto crash

### ISSUE THREAD

**Issue by tioannidis** [ColdGrub1384/Pyto#162]
It seems that pyto doesn't handle memory errors in some cases and crashed without message... Here is an example of the code 

`result = [x+1 for x in range(1000000000)] `

I guess, Pyto should catch this exception and handle in the same way as pycharm

Regards,
Theo

![882E7E2B-7863-4568-A9EB-FCA8827436D0](https://user-images.githubusercontent.com/1592909/79900054-ef276880-840d-11ea-9a02-d3b417a98c64.jpeg)

**Comment by ColdGrub1384** [comment]
That would be very hard to implement. Computer IDEs run code on subprocesses, so if a script crashes, the IDE doesn't crash. But iOS doesn't allow to do that, so the script is executed in the app's context. Python supports setting memory limits with the `resources` modules but it does not work on macOS and so it doesn't work on iOS either.
