### ISSUE TITLE
Can libterm and pyto be used together for django projects?

### ISSUE THREAD

**Issue by iFrostFox** [ColdGrub1384/Pyto#170]
Hello, I’m trying to set up a django project at pyto, but as you know pyto doesn’t have a shell so I can’t run commands like “python manage.py startapp blog” I wonder if I could use Libterm (another app by the same developer) for running these commands and Pyto for editing the code.

Note:I’m also going to ask this question at libterm’s issues page

**Comment by cclauss** [comment]
Pyto allows you to pass in arguments when you run commands.  When looking at a Python file, click the ⚙️ icon at the lower right then click `Arguments`.

**Comment by iFrostFox** [comment]
cclauss, thanks for your fast reply, I know you can pass arguments by clicking the gear icon(it said at the pyto documentation. But I didn’t understand how can I run these commands. Should I paste the command at the arguments part.

Note:Sorry for the question I just started learning python, and I can’t understand these kind of explanations

**Comment by ColdGrub1384** [comment]
As @cclauss says, you can pass arguments to a script. But Pyto also has a kind of shell where you can run Python scripts with arguments. Here is how to use Django on Pyto: https://pyto.readthedocs.io/en/latest/django.html

**Comment by iFrostFox** [comment]
Thanks for your reply. Ultimately I wanted to ask how can I use the ‘createsuperuser‘ command. When I try to use it is says`Superuser creation skipped due to not running in a TTY. You can run manage.py createsuperuser in your project to create one manually.`. I wonder how can I use that command.

**Comment by ColdGrub1384** [comment]
The command doesn't work because the Pyto console doesn't have the features of a terminal. You can use this code to create a superuser:

```python
from django.contrib.auth.models import User
User.objects.create_superuser(username='username', password='password', email='email')
```

https://stackoverflow.com/a/48603387
