### ISSUE TITLE
run on the iPhone, master branch , dyld: Symbol not found:  , app crash

### ISSUE THREAD

**Issue by JunyiXie** [ColdGrub1384/Pyto#171]
dyld: Symbol not found: ZN2cv3dnn14dnn4_v202003105Layer10initHalideERKNSt316vectorINS_3PtrINS1_14BackendWrapperEEENS3_9allocatorIS7_EEEE
  Referenced from: /var/containers/Bundle/Application/41D5F6AD-3C15-4AC0-9FE6-0089C772A1B5/Pyto.app/Pyto
  Expected in: flat namespace
 in /var/containers/Bundle/Application/41D5F6AD-3C15-4AC0-9FE6-0089C772A1B5/Pyto.app/Pyto
(lldb)
master branch , run  in iphone, crash. Can someone help me?

**Comment by ColdGrub1384** [comment]
Download this: https://github.com/ColdGrub1384/OpenCV-Contrib-iOS/releases/download/4.3.0/opencv2.framework.zip And put `opencv2.framework` inside the OpenCV folder and it should work
