### ISSUE TITLE
Can I kick off a Ptyo script from the share extension in another app?

### ISSUE THREAD

**Issue by halloleo** [ColdGrub1384/Pyto#172]
One feature I really liked in the "good old" Pythonista app was how I could activate scripts from the share extension in another apps and give it parameters like URLs, text or images to process. 

Is this possible with Pyto as well? And if so, how? Couldn't find anything in the docs.

**Comment by ColdGrub1384** [comment]
It's not possible for the moment, but a workaround is to use Shortcuts. You can run code with arguments. You can also import a script in `sys.path` for example.
![IMG_69CC65941CA6-1](https://user-images.githubusercontent.com/19255527/80893687-8f00b400-8ca2-11ea-8578-dd8b5c131fd2.jpeg)

**Comment by ColdGrub1384** [comment]
This is a Shortcut to download a Youtube video from the share sheet: https://www.icloud.com/shortcuts/5912d56a86364c47a617043151208636

**Comment by halloleo** [comment]
Thanks @ColdGrub1384. Going via shortcuts is certainly a feasible workaround.

**Comment by cclauss** [comment]
Can we close this issue?

**Comment by halloleo** [comment]
Done.
