### ISSUE TITLE
How do I share a string with sharing.share_items ?

### ISSUE THREAD

**Issue by kevinp2** [ColdGrub1384/Pyto#175]
Hi,

I have constructed a string in my Pyto script. I want to then have the script bring up the Share dialog so that this string can be easily shared via email, text message, etc.

`pasteboard.set_string ( mystring ) 
`
works perfectly and I can then paste into any iOS app.

But this crashes the pyto app:

`sharing.share_items ( mystring )
`
Any suggestions are appreciated!

**Comment by ColdGrub1384** [comment]
Hi,

`share_items` takes an array as input. Try `sharing.share_items([mystring])`

**Comment by kevinp2** [comment]
That worked very well, thank you!  

A follow on question:  When the Share dialog pops up on iOS, if the user selects Mail, then the text string is placed into the body of the email.  This works.  But is it possible to specify a different string for the subject line of the email?  All my news apps seem to be able to do this. 

I know, I know, I am getting greedy :-)

**Comment by cclauss** [comment]
Can we close this issue as solved?

**Comment by ColdGrub1384** [comment]
@kevinp2 It’s not possible with Pyto, but I just found it’s technically possible. I may add that as a feature. I’ll close the issue.
