### ISSUE TITLE
Is this still true?

### ISSUE THREAD

**Issue by OldSubSailor** [ColdGrub1384/Pyto#176]
https://github.com/ColdGrub1384/Pyto/issues/1#issuecomment-432625529

**Comment by cclauss** [comment]
That issue was closed in 2018 so it is safe to say the many of the statements in #1 have changed in the past two years.  Was there a particular statement in #1 that you are curious about?

**Comment by OldSubSailor** [comment]
Howdy,
This was the one:
If you already have Pythonista, you shouldn't try Pyto. Pythonista is better than Pyto but Pyto is open source.

**Comment by cclauss** [comment]
I own them both.  I use them for different thing and the costs are quite resonable.
