### ISSUE TITLE
Watch app crashes on startup 

### ISSUE THREAD

**Issue by cloudmartin** [ColdGrub1384/Pyto#188]
As title. The watch extension never successfully starts.  

Logs:
{"bug_type":"109","os_version":"Watch OS 6.2.5 (17T608)","build_version":"3","timestamp":"2020-05-29 09:30:38.00 +0100","app_name":"Pyto Watch Extension","bundleID":"ch.marcela.ada.Pyto.watchkitapp.watchkitextension","incident_id":"640B4458-9DB0-4BD4-B981-1ACD9A01AC7E","name":"Pyto Watch Extension","is_first_party":0,"app_version":"12.0","share_with_app_devs":0,"slice_uuid":"82a54709-c912-3aa6-b244-72581a383cff","adam_id":1436650069}
Incident Identifier: 640B4458-9DB0-4BD4-B981-1ACD9A01AC7E
CrashReporter Key:   dbf9966ed8d79eb9a06fc669702475952bf076c1
Hardware Model:      Watch3,4
Process:             Pyto Watch Extension [568]
Path:                /private/var/containers/Bundle/Application/F0022128-D9CB-4ADC-8FFA-60DD8E7ABC51/Pyto Watch.app/PlugIns/Pyto Watch Extension.appex/Pyto Watch Extension
Identifier:          ch.marcela.ada.Pyto.watchkitapp.watchkitextension
Version:             3 (12.0)
AppVariant:          1:Watch3,4:6
Code Type:           ARM (Native)
Role:                Foreground
Parent Process:      launchd [1]
Coalition:           ch.marcela.ada.Pyto.watchkitapp.watchkitextension [339]

Date/Time:           2020-05-29 09:30:36.0275 +0100
Launch Time:         2020-05-29 09:30:35.0000 +0100
OS Version:          Watch OS 6.2.5 (17T608)
Release Type:        User
Baseband Version:    n/a
Report Version:      104

Exception Type:  EXC_CRASH (SIGABRT)
Exception Codes: 0x0000000000000000, 0x0000000000000000
Exception Note:  EXC_CORPSE_NOTIFY
Termination Reason: Namespace WATCHKIT, Code 0x1
Triggered by Thread:  0

Thread 0 name:  Dispatch queue: com.apple.main-thread
Thread 0 Crashed:
0   libsystem_kernel.dylib        	0x43e2d7ac 0x43e12000 + 112556
1   libsystem_kernel.dylib        	0x43e32978 0x43e12000 + 133496
2   libsystem_kernel.dylib        	0x43e32932 0x43e12000 + 133426
3   WatchKit                      	0x536590aa 0x535b3000 + 680106
4   libdispatch.dylib             	0x43cd2e1e 0x43cce000 + 19998
5   libdispatch.dylib             	0x43cd3ed0 0x43cce000 + 24272
6   WatchKit                      	0x535ce434 0x535b3000 + 111668
7   WatchKit                      	0x535ce30c 0x535b3000 + 111372
8   UIKitCore                     	0x5c1a785e 0x5b9d8000 + 8190046
9   UIKitCore                     	0x5c1acc7c 0x5b9d8000 + 8211580
10  UIKitCore                     	0x5bb5b8ee 0x5b9d8000 + 1587438
11  UIKitCore                     	0x5bed92b4 0x5b9d8000 + 5247668
12  UIKitCore                     	0x5bb5c1de 0x5b9d8000 + 1589726
13  UIKitCore                     	0x5bb5bc9c 0x5b9d8000 + 1588380
14  UIKitCore                     	0x5bb5c080 0x5b9d8000 + 1589376
15  UIKitCore                     	0x5bb5ba66 0x5b9d8000 + 1587814
16  UIKitCore                     	0x5bb5f518 0x5b9d8000 + 1602840
17  UIKitCore                     	0x5be2f9d8 0x5b9d8000 + 4553176
18  UIKitCore                     	0x5bef01bc 0x5b9d8000 + 5341628
19  UIKitCore                     	0x5bb5f338 0x5b9d8000 + 1602360
20  UIKitCore                     	0x5bef00cc 0x5b9d8000 + 5341388
21  UIKitCore                     	0x5bb5f1dc 0x5b9d8000 + 1602012
22  UIKitCore                     	0x5ba0f362 0x5b9d8000 + 226146
23  UIKitCore                     	0x5ba0e2d8 0x5b9d8000 + 221912
24  UIKitCore                     	0x5ba0f0ec 0x5b9d8000 + 225516
25  UIKitCore                     	0x5c1ab24c 0x5b9d8000 + 8204876
26  UIKitCore                     	0x5be4bc06 0x5b9d8000 + 4668422
27  PepperUICore                  	0x4e410928 0x4e34d000 + 801064
28  CarouselUIServices            	0x51abff08 0x51a9d000 + 143112
29  FrontBoardServices            	0x473f41aa 0x473e7000 + 53674
30  FrontBoardServices            	0x47412ff0 0x473e7000 + 180208
31  FrontBoardServices            	0x473fd00c 0x473e7000 + 90124
32  FrontBoardServices            	0x47412d3c 0x473e7000 + 179516
33  libdispatch.dylib             	0x43cd2e1e 0x43cce000 + 19998
34  libdispatch.dylib             	0x43cd507a 0x43cce000 + 28794
35  FrontBoardServices            	0x47431748 0x473e7000 + 304968
36  FrontBoardServices            	0x4743152e 0x473e7000 + 304430
37  FrontBoardServices            	0x47431926 0x473e7000 + 305446
38  CoreFoundation                	0x44156a7e 0x440d2000 + 543358
39  CoreFoundation                	0x441569d4 0x440d2000 + 543188
40  CoreFoundation                	0x441563aa 0x440d2000 + 541610
41  CoreFoundation                	0x44152374 0x440d2000 + 525172
42  CoreFoundation                	0x44151dfc 0x440d2000 + 523772
43  GraphicsServices              	0x46fbbd3c 0x46fb9000 + 11580
44  UIKitCore                     	0x5c1aea9e 0x5b9d8000 + 8219294
45  libxpc.dylib                  	0x43ef3f1c 0x43ed6000 + 122652
46  libxpc.dylib                  	0x43ee4f3c 0x43ed6000 + 61244
47  libxpc.dylib                  	0x43ee6b98 0x43ed6000 + 68504
48  Foundation                    	0x44a67090 0x44a2d000 + 237712
49  PlugInKit                     	0x4bc3c392 0x4bc2a000 + 74642
50  WatchKit                      	0x535cdaf0 0x535b3000 + 109296
51  libdyld.dylib                 	0x43d0d7b2 0x43d0a000 + 14258

Thread 1:

**Comment by ColdGrub1384** [comment]
Fixed in the last update. Thanks
