### ISSUE TITLE
[Question] How to get the selected range of a TextView?

### ISSUE THREAD

**Issue by onyxware** [ColdGrub1384/Pyto#189]
I am trying to port StaSh to Pyto, and I am in the process of subclassing `ShTerminal` ([porting_guide](https://github.com/ywangd/stash/blob/master/docs/porting_guide.md)). However, it seems pyto_ui.TextView does not have a “selected_range” attribute. Is there any way I can get the range of selected text?

```
import pyto_ui, mainthread

tv = pyto_ui.TextView

@mainthread.mainthread
def present():
    pyto_ui.show_view(tv, mode=pyto_ui.PRESENTATION_MODE_SHEET)

present()
# get selected text as a two-tuple of (start, end)???
```

See [this](https://omz-software.com/pythonista/docs/ios/ui.html#ui.TextView) for the Pythonista equivalent of TextView (which has the selected_range attribute).

**Comment by iFrostFox** [comment]
I haven’t fully understood what do you want to do, what do you mean by start and end?

**Comment by ColdGrub1384** [comment]
There is not yet a function to do that.

**Comment by onyxware** [comment]
Ok, thank you! Now, the change just needs to be pushed to the beta.
