### ISSUE TITLE
os.system(‘cls’) it prints -1 instead of clearing the console

### ISSUE THREAD

**Issue by iFrostFox** [ColdGrub1384/Pyto#193]
When I run os.system(‘cls’) is prints an -1 wich has a link to [pyto://inspector/-1%0A/?%7B%220%22:%20%22-1%22%7D](pyto://inspector/-1%0A/?%7B%220%22:%20%22-1%22%7D)
How can I clear the console? Also why does it print -1 with the link?

**Comment by cclauss** [comment]
-1 because the command failed with an error code of -1

**Comment by iFrostFox** [comment]
I recently tried```subprocess.call(‘cls’)``` but it gave an PermissonError

Full Error:
```Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "Library/python38/subprocess.py", line 340, in call
    with Popen(*popenargs, **kwargs) as p:
  File "Library/python38/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "Library/python38/subprocess.py", line 1637, in _execute_child
    self.pid = _posixsubprocess.fork_exec(
PermissionError: [Errno 1] Operation not permitted```

**Comment by ColdGrub1384** [comment]
Pyto cannot run subprocesses as any iOS app. The link opens a value inspector. Each value in the REPL can be tapped to see an object or module properties.

**Comment by iFrostFox** [comment]
Is there any other command that works with pyto to clear the console?

**Comment by ColdGrub1384** [comment]
In the repl, calling `clear()` works. In a script: `from console import clear; clear()`

**Comment by iFrostFox** [comment]
Thanks, It works
