### ISSUE TITLE
Support for psycopg2

### ISSUE THREAD

**Issue by mtama90** [ColdGrub1384/Pyto#196]
Succesfully install psycopg2, when import no module named psycopg2._psycopg. please help

**Comment by enquora** [comment]
From the PyPi description: "Psycopg 2 is mostly implemented in C as a libpq wrapper". Only pure Python packages can be installed using Pyto's pip command. Consider using the pure Python pg8000 PostgreSQL package. It is on PyPi.

If the project owner is considering including psycopg2, I would suggest instead the asyncpg package - it is far faster and more effective at executing queries which return large result sets.

**Comment by mtama90** [comment]
Thank you for the help @enquora 👍
