### ISSUE TITLE
boto3 s3 error

### ISSUE THREAD

**Issue by DevOpsEtc** [ColdGrub1384/Pyto#198]
I'm testing out AWS API access and have encountered a problem when setting up an s3 client connection. It's throwing a ModuleNotFoundError: No module named 's3transfer'. I did try a "pip install s3transfer", then a corresponding "import s3transfer" inside the script, but it did not resolve the problem. My other client connections (sts and ec2 ) are working as expected.

I'm on an iPad Pro (12.9-inch, 3rd generation, iPad OS version 13.4.1) using Pyto version 12.1 (4).

**Traceback:**
�[31mTraceback (most recent call last):Traceback (most recent call last):
File "Pyto.app/site-packages/extensionsimporter.py", line 1114, in load_module
mod = importlib.import(fullname)
File "", line 1093, in import
File "", line 1014, in _gcd_import
File "", line 991, in _find_and_load
File "", line 975, in _find_and_load_unlocked
File "", line 671, in _load_unlocked
File "", line 783, in exec_module
File "", line 219, in _call_with_frames_removed
File "compiled/boto3/s3/inject.py", line 15, in 
File "compiled/boto3/s3/transfer.py", line 127, in 
ModuleNotFoundError: No module named 's3transfer'

**Python script:**

```
import boto3
import _private.env

session = boto3.Session(
    aws_access_key_id = _private.env.ACCESS_KEY,
    aws_secret_access_key = _private.env.SECRET_KEY
)

sts_client = session.client('sts')
response = sts_client.get_caller_identity()
print('AWS Account ID:\t\t', response['Account'])

ec2_client = session.client('ec2', 'us-west-2')
response = ec2_client.describe_instances(Filters=
    [
        {'Name' : 'tag:Name','Values' : ['aws-cloud9*']},
        {'Name' : 'instance-state-name','Values' : ['stopped']}
    ]
)
print('Cloud9 Instance ID:\t', response["Reservations"][0]['Instances'][0]['InstanceId'])

s3_client = boto3.resource('s3')
for bucket in s3_client.buckets.all():
    print (bucket.name)
```

**Comment by mtama90** [comment]
I also facing this problem. Please help

**Comment by ColdGrub1384** [comment]
I figured out what was the problem. I'll release a fix. For the moment, you can install `s3transfer` manually. Download the package, unarchive it, and place it in `On my iPhone / iPad > Pyto > site-packages`

https://files.pythonhosted.org/packages/50/de/2b688c062107942486c81a739383b1432a72717d9a85a6a1a692f003c70c/s3transfer-0.3.3.tar.gz

**Comment by mtama90** [comment]
I try to put package in site, got another error I think: 
ModuleNotFoundError: No module named 's3transfer.exceptions'

**Comment by cclauss** [comment]
https://github.com/boto/s3transfer/blob/develop/s3transfer/exceptions.py

**Comment by mtama90** [comment]
Thank you, it is working now

**Comment by ColdGrub1384** [comment]
It's working now on the last update.

**Comment by DevOpsEtc** [comment]
@ColdGrub1384, PyPi install followed by import works great for me now... thanks for fixing! I have now replaced Pythonista entirely with Pyto. Please consider adding line comment toggling.
