### ISSUE TITLE
Tried to import numpy but error encountered

### ISSUE THREAD

**Issue by sausheong** [ColdGrub1384/Pyto#2]
Got this error when using both REPL and trying to write a script:

ImportError

Error importing numpy: you should not try to import numpy from
        its source directory; please exit the numpy source tree, and relaunch
        your python interpreter from there.

**Comment by ColdGrub1384** [comment]
Do you have the App Store version or do you built it from the source?

**Comment by sausheong** [comment]
The app store version. 

Sau Sheong

**Comment by ColdGrub1384** [comment]
What device do you have? It should be related to the device since it works on my iPhone 7 and my iPad 5th gen. Someone tested on an iPhone XS also.

**Comment by ColdGrub1384** [comment]
Do you have a directory named "numpy"? It seems like Python is trying to import another numpy than the bundled one.

**Comment by ColdGrub1384** [comment]
Could you import these modules?

import __numpy_core_multiarray
import __numpy_core_umath
import __numpy_fft_fftpack_lite
import __numpy_linalg__umath_linalg
import __numpy_linalg_lapack_lite
import __numpy_random_mtrand

**Comment by sausheong** [comment]
I removed the app then re-installed it and everything seems ok. Thanks for the great feature!

Sau Sheong

**Comment by sausheong** [comment]
There is a ‘pandas’ package that is built-in but it’s actually not the Pandas I thought it would be. Will Pandas and matplotlib be in the future.

**Comment by ColdGrub1384** [comment]
Ok. Thank you for reporting the bug. 
I'm trying to add Pandas. There is a branch: https://github.com/ColdGrub1384/Pyto/tree/pandas. But it's not yet working. The problem is Pandas and Matplotlib (and also NumPy) have C code so it has to be compiled and loaded in a special way so just adding the package directory doesn't work on iOS.
The `pandas` directory shouldn't be there, it was added when I was trying to include it.
But I already compiled it, so it will probably work soon. I didn't tried yet Matplotlib, but I will try.

**Comment by cclauss** [comment]
Can this issue be closed?
```
Python 3.7.0+ (default, Jul  5 2018, 12:28:47) 
[Clang 9.1.0 (clang-902.0.39.2)] on ios
Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)
>>> import matplotlib, numpy, pandas
>>> matplotlib.__version__, numpy.__version__, pandas.__version__
('3.0.2', '1.16.1', '0.24.1')
>>> 
```

**Comment by ColdGrub1384** [comment]
Yes

**Comment by yjqiang** [comment]
> Can this issue be closed?
> ```
> Python 3.7.0+ (default, Jul  5 2018, 12:28:47) 
> [Clang 9.1.0 (clang-902.0.39.2)] on ios
> Type "help", "copyright", "credits" or "license" for more information.
> (InteractiveConsole)
> >>> import matplotlib, numpy, pandas
> >>> matplotlib.__version__, numpy.__version__, pandas.__version__
> ('3.0.2', '1.16.1', '0.24.1')
> >>> 
> ```
> @yjqiang

wow
