### ISSUE TITLE
subprocess.call(“python alert.py Hello!”) raises an Permisson Error

### ISSUE THREAD

**Issue by iFrostFox** [ColdGrub1384/Pyto#206]
I’m trying to run a file named `alert.py` from another file named `subprocess-demo.py` while passing arguments, the `alert.py` shows an alert which the title is the arguments passed, and the message is ‘message’ 

The files:

`subprocess-demo.py`:
```
import subprocess

subprocess.call('python alert.py Hello!')
```

`alert.py`:
```
import console
import sys

alert1 = console.Alert.alertWithTitle(str(*sys.argv[1:]), 'message')
alert1.addCancelAction('Cancel')
alert1.addAction('Ok')
alert1.show()
```

When I run the file with some arguments, it works fine, but when I call the file from `subprocess-demo.py` it gives this error:

```
Traceback (most recent call last):
  File "/private/var/mobile/Containers/Shared/AppGroup/27E9535B-31EC-4518-939F-6A46A7923622/File Provider Storage/subprocess-demo.py", line 3, in <module>
    subprocess.call('python alert.py Hello!')
  File "Library/python38/subprocess.py", line 340, in call
    with Popen(*popenargs, **kwargs) as p:
  File "Library/python38/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "Library/python38/subprocess.py", line 1637, in _execute_child
    self.pid = _posixsubprocess.fork_exec(
PermissionError: [Errno 1] Operation not permitted
```

I tried to use subprocess.call with other files and also tried subprocess.Popen but each gives the same error, why is this happening and how can I solve it?

**Comment by cclauss** [comment]
```
import sys
import subprocess
subprocess.call([sys.executable, 'alert.py', 'Hello!'])
```
Or https://docs.python.org/3/library/runpy.html but it might be _very_ possible that Apple's sandbox does not allow any of this.

**Comment by iFrostFox** [comment]
Thanks for your reply, but sadly your code doesn’t work either

**Comment by ColdGrub1384** [comment]
iOS apps aren't allowed to run subprocesses so the `subprocess` module cannot work. `runny` should work fine.

**Comment by iFrostFox** [comment]
Thanks

**Comment by cclauss** [comment]
Can we close this issue??
