### ISSUE TITLE
Matplotlib error when using internal function ._show()

### ISSUE THREAD

**Issue by PyMarc2** [ColdGrub1384/Pyto#207]
There’s a library ‘raytracing’ which uses internal commands .show() of matplotlib. It works juste fine on my computer, but it gives this error on ios.

`TypeError: _show() got an unexpected keyword argument 'block' `

Here’s a MWE
`

from raytracing import *

path = ImagingPath()
path.name = "Telescope"
path.append(Space(d=100))
path.display()

`

**Comment by PyMarc2** [comment]
Was this issue resolved?

**Comment by ColdGrub1384** [comment]
Yes: 9c79ace5fac16c5976006dd847feb5757331fd72. Thanks for the report. I'll release a new update soon.
