### ISSUE TITLE
Crash when interacting with read txt file object in editor

### ISSUE THREAD

**Issue by TheOfficialCzex** [ColdGrub1384/Pyto#223]
When running the following code, Pyto completely crashes when I move my cursor (whether with arrow keys or tapping) to the "text" object in the editor. The code runs fine, but is not editable in regards to the "text" in the "num" and "res" lines. The top line is fine to interact with.

```
text = open("Flow.txt","r").read().split()
        
num = [text for text in text if len(text) < 2]
res = [text for text in text if len(text) > 2]
```

The opened list is a series of numbers separated by spaces and newlines. They have not been converted to ints and floats in the code.

printing "num" or "res" result in the expected outputs.

**Comment by cclauss** [comment]
The first line leaves a file handler open which is not a good idea...
* https://stackoverflow.com/questions/25070854/why-should-i-close-files-in-python

The remaining two lines modify and object while iterating over it.
* num = [text for text in text___s___ if len(text) < 2]

Does this code crash in the same way?
```python
with open("Flow.txt","r") as in_file:
    words = in_file.read().split()
        
num = [word for word in words if len(word) < 2]
res = [word for word in words if len(word) > 2]
```

**Comment by TheOfficialCzex** [comment]
@cclauss Excellent! Thank you so much. This fixes everything, and I learned a few things in the process.
