### ISSUE TITLE
Script Files without extension

### ISSUE THREAD

**Issue by 42sol-eu** [ColdGrub1384/Pyto#225]
We are using a project that is defining a python script without a .py extension.

Would it be possible to add this to Pyto (allow me to add scrip files without extensions)?

Thanks

**Comment by 42sol-eu** [comment]
Look at this https://actions.getdrafts.com/a/1dd

**Comment by cclauss** [comment]
The workaround for this is quite easy and has some nice advantages.  Put your code in a .py file and call it from a bare-bones file with no extension.  Running either file should deliver identical results.  In Pyto, you can run the .py file and on other platforms the file with no extension.

% __cat script__  # The bare-bones file with no extension.
```python
#!/usr/bin/env python3
from script import main ; main()
```
% __cat script.py__  # This is where your real code should be.
```python
#!/usr/bin/env python3

def main():
    print("I did my thing.")

if __name__ == "__main__":
    main()
```
% __./script.py__
```
I did my thing.
```
% __./script__
```
I did my thing.
```
The other advantage of this approach is that linters, formatters, test tools, pre-commit, editors, etc. will all find and properly process your Python code.

**Comment by 42sol-eu** [comment]
Totally true!
I got to that after writing the issue.

Another option is to call the script from runpy.

Opening and editing is better with your setup.

Thanks CCC

Cheers
  Andreas
