### ISSUE TITLE
Pyup suggests some dependency upgrades

### ISSUE THREAD

**Issue by cclauss** [ColdGrub1384/Pyto#23]
[__Pyup__](pyup.io) analysis of __requirements.txt__ in https://github.com/cclauss/Pyto-module-versions...
<img width="768" alt="png image" src="https://user-images.githubusercontent.com/3709715/54012282-ea561580-4175-11e9-82a9-36a7d1faa99b.png">

**Comment by cclauss** [comment]
Update certifi to 2019.3.9

**Comment by ColdGrub1384** [comment]
Ok, I will upgrade packages later, but, for NumPy and Matplotlib, I will wait until a bigger update.

**Comment by ColdGrub1384** [comment]
I've updated `six`, `progress`, `idna`, `distlib`, `colorama` and `chardet`. Thank you.

**Comment by cclauss** [comment]
Nice!  The new https://six.readthedocs.io/#six.ensure_binary ensure_str(), and ensure_text() functions are really helpful in porting code to Python 3.

**Comment by ColdGrub1384** [comment]
I updated `certifi`
