### ISSUE TITLE
Now that we have lxml, please consider adding beautifulsoup4

### ISSUE THREAD

**Issue by cclauss** [ColdGrub1384/Pyto#24]
The widely used web scraping tool https://pypi.org/project/beautifulsoup4/ which uses lxml.

**Comment by ColdGrub1384** [comment]
If I added lxml, it’s because it has C and Cython code, so it cannot be installed by pip. Other pure Python modules that are included are needed for Numpy, Matplotlib, Pandas, Pip or for apps modules. 
So, as beautifulsoup4 could be installed with pip, I don’t think it’s necessary to include it.

**Comment by ColdGrub1384** [comment]
I tried `pip install beautifulsoup4` and it worked, but I have and error on `pip install bs4`

**Comment by cclauss** [comment]
You __pip install beautifulsoup4__ and you __from bs4 import BeautifulSoup__ (confusing)!  You do not need to __pip install bs4__.

**Comment by ColdGrub1384** [comment]
Also, maybe `lxml` will not be possible on the App Store: #25

**Comment by cclauss** [comment]
For BeautifulSoup, I was able to do __pip install beautifulsoup4 html5lib__ which is slower than __lxml__ but it works OK for web scraping with Pyto.
