### ISSUE TITLE
App Store rejection for lxml

### ISSUE THREAD

**Issue by ColdGrub1384** [ColdGrub1384/Pyto#25]
Maybe `lxml` will not be possible on the App Store, `lxml` depends on `libxml`, `libxslt` and `libexslt` C libraries. They are already included on Xcode, no need to compile them. But, `lxml` calls many functions of `libxslt` and `libexslt` that aren't defined on header files (they are defined by headers inside `lxml`) and Apple says they are [Private APIs](https://stackoverflow.com/questions/17580251/what-exactly-is-a-private-api-and-why-will-apple-reject-an-ios-app-if-one-is-us).

> Dear Developer,

> We identified one or more issues with a recent delivery for your app, "Pyto - Python IDE". Please correct the following issues, then upload again.

> Non-public API usage:

> The app references non-public symbols in Pyto: _exsltDateXpathCtxtRegister, _exsltMathXpathCtxtRegister, _exsltRegisterAll, _exsltSetsXpathCtxtRegister, _exsltStrXpathCtxtRegister, _xsltApplyOneTemplate, _xsltApplyStylesheetUser, _xsltDocDefaultLoader, _xsltFreeSecurityPrefs, _xsltFreeStylesheet, _xsltFreeTransformContext, _xsltGetProfileInformation, _xsltGetSecurityPrefs, _xsltLibxsltVersion, _xsltMaxDepth, _xsltNewSecurityPrefs, _xsltNewTransformContext, _xsltNextImport, _xsltParseStylesheetDoc, _xsltProcessOneNode, _xsltQuoteOneUserParam, _xsltRegisterAllExtras, _xsltRegisterExtElement, _xsltRegisterExtFunction, _xsltSaveResultTo, _xsltSaveResultToFilename, _xsltSaveResultToString, _xsltSecurityAllow, _xsltSecurityForbid, _xsltSetCtxtParseOptions, _xsltSetCtxtSecurityPrefs, _xsltSetGenericErrorFunc, _xsltSetLoaderFunc, _xsltSetSecurityPrefs, _xsltSetTransformErrorFunc, _xsltTransformError
If method names in your source code match the private Apple APIs listed above, altering your method names will help prevent this app from being flagged in future submissions. In addition, note that one or more of the above APIs may be located in a static library that was included with your app. If so, they must be removed.

> If you think this message was sent in error and that you have only used Apple-published APIs in accordance with the guidelines, send the app's nine-digit Apple ID, along with detailed information about why you believe the above APIs were incorrectly flagged, to appreview@apple.com. For further information, visit the Technical Support Information page.

I sent this email to Apple and will see if they allow me to publish the app with `lxml`:

> Hello,

> My app “Pyto - Python IDE” (1436650069), was rejected for Private APIs. 
I included “libxslt” and “libexslt” static libraries from the iOS SDK (directly added from Xcode, I didn’t downloaded it from anywhere). The private symbols are from these libraries. 
I need libxslt and libexslt for another static library (that I downloaded and compiled). This library is a quite important part of the app. The app is for coding Python, so by adding this library, I can make work a Python library using it. libxslt and libexslt libraries are public and open source. So, they don’t really have Apple Private APIs. I don’t see any reason for rejecting that.

**Comment by scoder** [comment]
Wouldn't a static build of lxml work here? It obviously increases the binary size, but as long as that's acceptable for the use case at hand …

**Comment by ColdGrub1384** [comment]
@scoder That’s what I did. The problem is that Apple doesn’t allow the use of `libxslt` and `libexslt` on the App Store. I don’t know why...

**Comment by goodclass** [comment]
I have compiled LXML, and if you need it, I'll upload it later. Apple may first load the system libraries and then have its own static libraries, all of which lead to links being private. I changed the derived function into my own. This will load private functions.

**Comment by goodclass** [comment]
https://github.com/goodclass/lxml_arm64

**Comment by ColdGrub1384** [comment]
Thank you so much! I will try to publish to TestFlight to see if it works.

**Comment by ColdGrub1384** [comment]
@goodclass It worked!! A new beta will be released soon! Thank you so much for the help!

**Comment by goodclass** [comment]
You are welcome. 
I'm very grateful to Pyto for bringing me tremendous growth. I just solved a little problem. 
Lxml compilation method: I refer to the libxslt and lxml source code to the Xcode project, to do a global replacement of dozens of methods above. For example, exsltRegisterAll is replaced by MyexsltRegisterAll. This is a manual work, but the operation is also completed quickly. Recently make.
If you encounter problems, you need library source code, I can also provide it. It's just a little bit of modification.

**Comment by ColdGrub1384** [comment]
Here is the link :) https://testflight.apple.com/join/Kts3HqEj Thank you again!

**Comment by cclauss** [comment]
Nice teamwork here!
