### ISSUE TITLE
Importing a module in the same folder fails

### ISSUE THREAD

**Issue by victordomingos** [ColdGrub1384/Pyto#27]
It is not clear if the files already have a .py extension. I noticed that when I added the extension myself to new files and started getting import errors. Renaming the file and removing the extension solves the issue, but it should be more transparent for the user.

**Comment by ColdGrub1384** [comment]
Extensions are hidden on this app because it's an app for coding Python. For example, on Swift Playgrounds, the `playground` or `playgroundbook` extensions are hidden. There are previews. Other file types are displayed by their icon and not by preview.
