### ISSUE TITLE
Crash while installing Astroplan

### ISSUE THREAD

**Issue by victordomingos** [ColdGrub1384/Pyto#28]
While trying to install The `astroplan` package from PyPI, the Pyto app displays some text about setuptools (just for a fraction of a second) and then crashes, returning into the iOS springboard.

**Comment by ColdGrub1384** [comment]
I will debug that. Thank you for reporting.

This should not cause the crash, but you cannot install this library as it depends on `astropy`, which has C code and the app can only install pure Python modules as it says on the App Store page. I will release an update that will disable the Install button for not pure Python modules, so it's clear when a module cannot be installed.

**Comment by ColdGrub1384** [comment]
Fixed by b54ff204f164ab07505ff3a9537e73529272bb57. I fixed the crash, but the module cannot be installed.
