### ISSUE TITLE
Cannot extract python.tar.gz

### ISSUE THREAD

**Issue by ForceBru** [ColdGrub1384/Pyto#30]
I run the following:

```
git clone https://github.com/ColdGrub1384/Pyto.git && cd Python && ./setup.sh
```

It gave me the following errors:

```
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   605    0   605    0     0    940      0 --:--:-- --:--:-- --:--:--   940
100  112M  100  112M    0     0  10.5M      0  0:00:10  0:00:10 --:--:-- 12.4M
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 51.7M  100 51.7M    0     0  6641k      0  0:00:07  0:00:07 --:--:-- 9404k
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0 55.3M    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0Warning: Failed to create the file Pyto Mac/python.tar.gz: No such file or 
Warning: directory
  0 55.3M    0 16360    0     0  11597      0  1:23:22  0:00:01  1:23:21 11602
curl: (23) Failed writing body (0 != 16360)
tar: Error opening archive: Failed to open 'Pyto Mac/python.tar.gz'
rm: Pyto Mac/VERSIONS: No such file or directory
rm: Pyto Mac/python.tar.gz: No such file or directory
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.1/lib/cocoapods/command.rb:118:in `git_version': Failed to extract git version from `git --version` ("git version 2.19.GIT\n") (RuntimeError)
	from /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.1/lib/cocoapods/command.rb:130:in `verify_minimum_git_version!'
	from /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.1/lib/cocoapods/command.rb:49:in `run'
	from /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.1/bin/pod:55:in `<top (required)>'
	from /usr/local/bin/pod:22:in `load'
	from /usr/local/bin/pod:22:in `<main>'
Submodule 'InputAssistant' (https://github.com/IMcD23/InputAssistant.git) registered for path 'InputAssistant'
Submodule 'ios_system' (https://github.com/ColdGrub1384/ios_system.git) registered for path 'ios_system'
Cloning into '/Users/forcebru/Desktop/python/Pyto/InputAssistant'...
Cloning into '/Users/forcebru/Desktop/python/Pyto/ios_system'...
Submodule path 'InputAssistant': checked out 'da9992049898becb8acfa764e2d3ace1276ac0a7'
Submodule path 'ios_system': checked out '0382ebc3a4a10c87b130c198e1a898f8070c2cf9'
```

As one can see, it says: `Warning: Failed to create the file Pyto Mac/python.tar.gz: No such file or directory`. There are other issues with the (nonexistent) `Pyto Mac` directory.

As far as I understand, these errors come from this line and the lines after it:
https://github.com/ColdGrub1384/Pyto/blob/15536ea428e8d6ab36292c27b973f853d5fedf96/setup.sh#L40

I think these commands should use `Pyto_Mac`, not `Pyto Mac`, provided that the Xcode project still fails to find files in the `Pyto_Mac/python` directory if I create the `Pyto Mac` directory and download everything there. However, if I download this into `Pyto_Mac`, everything works fine.

Well, except for the `pod` command. I've opened an [issue](https://github.com/CocoaPods/CocoaPods/issues/8661) about that as well, but probably I'm just being stupid.

**Comment by ColdGrub1384** [comment]
Oops, I renamed `Pyto Mac` folder to `Pyto_Mac`, I will fix it now. For the Cocoapods issue, it doesn't seem to be a problem of this project. As I see on the issue you have opened in the CocoaPods repo, you fixed it temporarily. You can create a file `~/.bashrc` if it doesn't exist and then put `export PATH=/usr/local/bin:$PATH` on it. This should run `export PATH=/usr/local/bin:$PATH` every time a terminal window is opened.

**Comment by cclauss** [comment]
Can we please keep the underscore?  Directories with spaces are a pain.

**Comment by ColdGrub1384** [comment]
Yes. That's why I renamed `Pyto Mac` to `Pyto_Mac`. But I forgot to rename it on the script.
