### ISSUE TITLE
Toggle if line is commented out or not keyboard shortcut

### ISSUE THREAD

**Issue by jammin0921** [ColdGrub1384/Pyto#34]
Is there a hardware key shortcut for toggling if a line is commented out or not from anywhere within the line?

Really enjoying it! Impressive work!

**Comment by ColdGrub1384** [comment]
There is no shortcut for that for the moment, but I will add it.

**Comment by cclauss** [comment]
It would be a nice addition to the on-screen keyboard too.

**Comment by ColdGrub1384** [comment]
Done! 4a723885f8675d08510e0030fcb376317ee1a8a1

The shortcut will be `⌘↑C`, and on the context menu, a "Toggle Comment" button is shown.
