### ISSUE TITLE
Module request: black

### ISSUE THREAD

**Issue by cclauss** [ColdGrub1384/Pyto#38]
https://github.com/python/black has been moved into the __Python GitHub domain__ so it would be nice if Pyto shipped with it installed.  It would be great to have both automatic and manual (a button or menu item) ways to invoke Black on Python files in Pyto.

**Comment by ColdGrub1384** [comment]
Great! I will work on it. I will put a button on the editor, and I could add something at the menu to simulate `python -m` for running scripts

**Comment by cclauss** [comment]
It would be cool if this button/menu approach was user configurable.  Some user might want to run [__futurize --stage1 -w__](http://python-future.org/automatic_conversion.html) on the current source file in the editor while another user might want to only run __futurize -f libfuturize.fixes.fix_print_with_import -w__ to only fix the legacy __print__ statements.

It would be cool if each of these users could configure/customize their Pyto buttons/menus via a .toml file or something similar without having to bring each of their requests back to you.

**Comment by cclauss** [comment]
I am excited to try it out!  Thanks.
