### ISSUE TITLE
How do I install a PyPI module but not the latest release?

### ISSUE THREAD

**Issue by cclauss** [ColdGrub1384/Pyto#43]
How would I install into Pyto the 0.6.0 release instead of the current 0.7.0?

https://pypi.org/project/dephell/#history shows the PyPI releases for a module.

**Comment by ColdGrub1384** [comment]
It’s possible to run a custom `pip` command. To do so, press `⚫️⚫️⚫️` from the main screen and then `Run module (python -m)`. After that, type `pip install dephell==0.6.0`.
