### ISSUE TITLE
Suggestion: Adjustable Output Window

### ISSUE THREAD

**Issue by jammin0921** [ColdGrub1384/Pyto#46]
I noticed that it's hard to view the head of a dataframe in the output window, even when setting the display option to more columns, which are just shown downward. I've included two screenshots below to show you what I mean. 

Have you thought about making the output window adjustable horizontally to include more output? There is a good amount of space between the code and the output that could be used for either longer code (which I'm assuming is what it's current use is) or output. 

What about a slide over window like on the iPhone app? Although some people may enjoy looking at their output and code at the same time. 

![IMG_5BBD123F19C1-1](https://user-images.githubusercontent.com/33337632/58262305-aa97d680-7d3f-11e9-8161-d819c750f130.jpeg)

![IMG_24640FE28736-1](https://user-images.githubusercontent.com/33337632/58262808-8ee10000-7d40-11e9-8261-d31c93a8c41a.jpeg)

**Comment by cclauss** [comment]
I agree with this need.  We should be able to slide the partition between the __editor__ and the __output__ panes without restriction.  Sometimes I only want to look at code and other times I only want to look at output and other times I want to see them both.

It would also be nice to have a button that lets me toggle from a side-to-side representation to an above-and-below representation.  Having code in the upper pane and output is the lower pane is equally valid and when trying to understand wide data which is generated by little code (bs4), the above-and-below representation would be quite appealing.

**Comment by ColdGrub1384** [comment]
I will work on it.

**Comment by ColdGrub1384** [comment]
Done 4e40c124be8b4d51bdc88ed7ff6a9664a82e1409

**Comment by jammin0921** [comment]
Adjustable window works really well! Thanks!

**Comment by cclauss** [comment]
Is this feature gone again in the current version?

**Comment by ColdGrub1384** [comment]
@cclauss Try to drag to the right and then to the left. However, when the console is shown at the bottom it should work well. It’s fixed on an update I’m working on, but this workaround should work for now.
