### ISSUE TITLE
Hardware Keyboard Tab Key

### ISSUE THREAD

**Issue by jammin0921** [ColdGrub1384/Pyto#47]
What about using the tab key to autocomplete code? I see that you've already listed the suggestions for touch selection at the bottom.

**Comment by ColdGrub1384** [comment]
But pressing the tab key would not indent. I think something like CMD+Tab would be better.

**Comment by jammin0921** [comment]
Is there a way to implement both? Like if the cursor is at the beginning of the line, pressing the tab key becomes a tab/set of space, but if it’s after a word or partial words, it shows the suggestions? Or after a . (Period) it shows the methods available?

**Comment by ColdGrub1384** [comment]
Oh yes, tabs are only used at the beginning of the line, so it would be okay to use it for code completion.

**Comment by ColdGrub1384** [comment]
Done 131438c9cb700c86834a2dc567b8b837279e7857
