### ISSUE TITLE
Module Installation Problem: ccxt

### ISSUE THREAD

**Issue by Tezeug** [ColdGrub1384/Pyto#48]
Hello.
I need to install the CCXT Python3 module. Your application shows that it should has been already installed but I get an error when I try to import it.
Thanks for help.

By the way, I am using the paid version of the application from the App Store.

![IMG_0004](https://user-images.githubusercontent.com/48736723/58344537-d59b2c80-7e0a-11e9-9dec-bde42f5b6154.png)
![IMG_0005](https://user-images.githubusercontent.com/48736723/58344539-d59b2c80-7e0a-11e9-86f8-b610dfa549f4.png)

**Comment by Tezeug** [comment]
UPDATE: I have restarted the application and it works greatly, thank you very much. Just curious, which version of Python did you integrate into the application? Is it the newest 3.7.3? Thanks again. I will let the “issue" opened to let you know about that.

**Comment by cclauss** [comment]
```python
import sys
print(sys.version_info)
```

**Comment by cclauss** [comment]
Please close this issue if you have a solution.

**Comment by Tezeug** [comment]
Thanks. I have found a solution. I have removed the module, installed it again and restarted the application. Then it started working. Hope this helps someone else, too if needed.

**Comment by ColdGrub1384** [comment]
Thank you. I tried to install the module and it worked at first time for me, it seems the bug is caused "randomly" and not each time the module is installed. If I found the problem, I will fix it. Python version is 3.7.0.
