### ISSUE TITLE
[Question] Working While Running

### ISSUE THREAD

**Issue by Tezeug** [ColdGrub1384/Pyto#49]
Hello.
This is not quite an issue rather than a question. Can I work on another Python script while I am running another? I am not sure whether the current running script will not stop. I mean just work on it, not run the second one too. Hope you understand what I mean.
Thanks.

**Comment by ColdGrub1384** [comment]
Hi. It’s currently not possible, the current running script is stopped before editing an other script. A workaround for now could be catching `SystemExit`, but that would not be useful in most of cases and the Stop button would not stop the script.

**Comment by cclauss** [comment]
When Python 3.8 comes our around at yearend, it will add some interesting capabilities in this regard.  https://hackernoon.com/has-the-python-gil-been-slain-9440d28fa93d  Implementing that on iOS might be held up by Apple's app policies.

**Comment by goodclass** [comment]
I think it's possible.
Multiple files are edited and run at the same time and output to the corresponding console.
My idea is to pass in the console name when running the script

`def run_script (path, consoleName):`
> `Thread = threading. Thread (target = run, args = (path, consoleName,))`

Start a console thread to run the script, and then intercept thread creation
`def run (url, consoleName):`
> `oldthead = threading. thread. _init__`
`def thread (...):`
>>`self. consoleName = consoleName`
>> `return oldthead (...)`

>`threading.thread. _init_ = thread`

This way, all subthreads will have an attribute consoleName
Final processing of output information
>`def printInfo (* objects, SEP = None, end = None):`
>>`td = threading. current_thread()`
`name = 'main'`
`If hasattr (td,'consoleName'): name = td. consoleName `
`PyInterface. printInfo (sep. join (array) +end, pid = name)`

The test passed, but I don't know if there will be any other situation. Another problem is the `_thread. start_new_thread` function. I don't know how to intercept it.

**Comment by Tezeug** [comment]
Thanks for help.

**Comment by ColdGrub1384** [comment]
@goodclass That would allow multiple scripts to run at same time. But I think @Tezeug would like to just see the output of another running script while editing, right?

**Comment by ColdGrub1384** [comment]
@goodclass Anyway I think that would be a very cool feature!

**Comment by goodclass** [comment]
There are some differences in language translation.
To make an analogy, a web server, a script running server, multiple running clients, if there is only one file running, this web function can not be realized.
First deal with threading
[thread_test.py](https://github.com/goodclass/PytoDemo/blob/master/thread_test.py)
You may try this script with threads. After the main thread is finished, the sub-threads are still active. Then you may run the script again. There will be threads running the script at the same time, indicating that different threads may be used to execute different scripts at the same time.

**Comment by Tezeug** [comment]
Alright. I would like to just edit another file but keep the first script running and see the output at the same time.

**Comment by Tezeug** [comment]
@ColdGrub1384

**Comment by ColdGrub1384** [comment]
I made that when a script is closed, it's automatically stopped because it takes some time to stop the script, but just generally just a second.

**Comment by ColdGrub1384** [comment]
I disabled that so scripts can be running while editing another one. 45a56dd70b84c8e743725b02f97e5309a23e36e1
