### ISSUE TITLE
Question Regarding White Console Box

### ISSUE THREAD

**Issue by jammin0921** [ColdGrub1384/Pyto#50]
On the output side of the screen, there’s a white box at the bottom that accepts text as an input. Is that box only for input when the script calls for input? Or is it a console spot to check variables and values of the environment when the script finishes? If it is not the latter, it may be useful as a console after running a script.

**Comment by ColdGrub1384** [comment]
It’s currently only for sending input to scripts and not for inspecting the environment, however, this can be done using the debugger with the bug button next to play. It uses `pdb`, you can set breakpoints and inspect the environment with or without breakpoints.

**Comment by jammin0921** [comment]
Okay thanks! Yeah I saw that the debugger uses pdb which I use a lot, so I’m a big fan of this. Are the commands the same? c -to continue, n -next line, etc? 

Oh and is there a hardware key stroke shortcut that can insert a breakpoint? 

Thanks!

**Comment by ColdGrub1384** [comment]
Yes, same commands. There isn’t a key stroke currently for setting a breakpoint but I can add it.

**Comment by jammin0921** [comment]
I think it would be very useful to have but not sure what a good key stroke combination would be for this.

**Comment by ColdGrub1384** [comment]
I have added Cmd+Shift+B. I think this is good because it’s similar to the key stroke combination for commenting a line, Cmd+Shift+/.
