### ISSUE TITLE
Would it be possible to use OpenCV?

### ISSUE THREAD

**Issue by cclauss** [ColdGrub1384/Pyto#52]
Controlling [OpenCV](https://github.com/opencv) with Python on an iOS device would be a superpower!!

**Comment by ColdGrub1384** [comment]
That would be great. I will try to implement it, but for the moment I’m busy coding an UI library, so I will try in some days.

**Comment by ColdGrub1384** [comment]
Done

**Comment by nylocx** [comment]
How would I use opencv with Pyto? Installing opencv-python from pip does not work.

**Comment by cclauss** [comment]
I would assume that OpenCV is preinstalled in the FlghtTest beta release and is not yet available in the AppStore release.

**Comment by cclauss** [comment]
@sombr

**Comment by kathrinkajderowicz** [comment]
Is openCV available on pythonista yet?

**Comment by cclauss** [comment]
This repo is about the iOS app Pyto which has OpenCV.  Pythonista is a different iOS app that does not have OpenCV.
