### ISSUE TITLE
[beta] Cannot return from Settings

### ISSUE THREAD

**Issue by mikaelho** [ColdGrub1384/Pyto#54]
Only way to get back from the Settings screen seems to be closing Pyto.

Latest beta on iOS 12.3.1, iPhone X.

**Comment by Ichicoro** [comment]
This only happens (for me) when changing the font size. Is it the same for you?

**Comment by mikaelho** [comment]
For me, it is consistent without any actions on the Settings screen.

**Comment by ColdGrub1384** [comment]
Yeah same thing for me. I will fix it.
