### ISSUE TITLE
Dice example version handling

### ISSUE THREAD

**Issue by mikaelho** [ColdGrub1384/Pyto#55]
Line 19, using `float` to convert version to number, breaks for minor iOS versions (xx.x.x).

**Comment by cclauss** [comment]
Would you be willing to submit a pull request?  https://github.com/ColdGrub1384/Pyto/blob/master/Pyto/Examples/User%20Interface/Dice.py

**Comment by ColdGrub1384** [comment]
Fixed by #56. Thanks!
