### ISSUE TITLE
Partial implementation of SciPy

### ISSUE THREAD

**Issue by goodclass** [ColdGrub1384/Pyto#61]
Hi, brother
scipy compiles IOS arm64

https://github.com/goodclass/scipy_arm64

Fortran code problems using F2C to C file http://www.netlib.org/f2c  converted C code run some problems.

Most of the C modules can run, only F2C modules have problems, later slowly trimming.

Some F2C modules can't run, otherwise they will crash, but SciPy depends on libraries. It seems that it does not affect other libraries such as `scikit-image`,  `scikit-learning`,  `statsmodels`. In the test application, I have done some tests, which may run normally.

I'm going to publish this method, and I hope you can work together to improve the correct operation of SciPy on IOS.

**Comment by ColdGrub1384** [comment]
Wow that's awesome! I will embed this to Pyto now. Great work!

**Comment by dalcacer** [comment]
Hi @goodclass, hi @ColdGrub1384 ,
I just stumbled over this issue and am pretty interested in compiling scipy on my own.
Is there re-producible build procedure that leads to the artefacts at https://github.com/goodclass/scipy_arm64 ? 
Regards
Dorian

**Comment by ColdGrub1384** [comment]
Hi @dalcacer,

I didn't compile SciPy myself, but I know the Fortran code was translated to C and then compiled. I think something like that: https://github.com/ktraunmueller/Computable/blob/2f802ff5a14628e425aae4ec14667d2f98c1fd75/python-ios/scripts/build-scipy.sh#L30
