### ISSUE TITLE
Relationship between inittab and PyImport_Module

### ISSUE THREAD

**Issue by eminarcissus** [ColdGrub1384/Pyto#64]
Hi,

Thanks for this great lib.

I've finished working with Scipy/sklearn etc before as well and looking forward to ship it without one of our app(we finally went with a different path on compiling Scipy, F2C caused us a lot of problems here and we gave up using it.) but finally we stopped to keep going on because the mammoth amount of so files need to wrap up might makes a App Store approvement really hard. But this approach looks quite promising.

One quick question here. seems like all modules dynamically loaded are manually registered with inittab as a builtin module. For example a code like this
PyImport_AppendInittab("__numpy_core_multiarray",multiarray_init_func);
Py_Initialize()
PyRun_SimpleString("import __numpy_core_multiarray;print(__numpy_core_multiarray)") will eventually print out something like this.
<module 'multiarray' (built-in)>
which is quite different with a module with a package name like "numpy.core.multiarray", looks like the package hierarchy is all lost here.

So here comes the problem, numpy init script have a lot of PyImport_Module("numpy.core.multiarray") or something like that. Should we patch all existence of those imports? Or I've missed out something here?

Really appreciate for your work here, thx very much :)

**Comment by eminarcissus** [comment]
Seems got it here, the magic happens in NumpyImporter, it redefines the path of the module it tries to import, thanks for the doc, it explains quite well :)

**Comment by ColdGrub1384** [comment]
@eminarcissus I will change the implementation method and just call `PyImport_AppendInittab` with the module path. That’s a lot easier. And that will fix relative imports from Cython, I replaced relative imports with absolute imports on Cython files, by simply calling `PyImport_AppendInittab` with module paths, that should be fixed. I didn’t know I could just use an absolute path if it was in a package.

**Comment by eminarcissus** [comment]
Module path? I've seen some discussion in Python's email list, seems like a full path like numpy.core.multiarray defined in PyImport_AppendInittab will not work since Python3, I did some test as well it won't work here, don't know if there are any method to make the package system in PyImport_AppendInittab working here, maybe the only way is to change the import logic?

**Comment by ColdGrub1384** [comment]
Ah 😅, that makes sense. I saw someone who did that but it was in Python 2.

**Comment by ColdGrub1384** [comment]
I think the import method should stay like that
