### ISSUE TITLE
Can't call "Run module"

### ISSUE THREAD

**Issue by 7points** [ColdGrub1384/Pyto#65]
After a function has been called from "Editor actions", "Run module (python -m)" will not work anymore, even after pyto has been restarted!

**Comment by ColdGrub1384** [comment]
Is there any error displayed? Which script are you running? `2to3` will not do anything if the script is already in Python 3.

**Comment by 7points** [comment]
no error displayed!

The issue is reproducible:
1. fresh installation of version 11.0 (7)
2. call "Run module (python -m)"
3. first line on REPL: Usage: <module-name> [<args>]
4. no Problem to run a programm like pip
5. Now create new file ("Hello world!")
6. call "Editor actions" --> black
7. answer: All done! ✨ 🍰 ✨ 1 file left unchanged.
8. Now try "Run module (python -m)" again
9. first line on REPL: All done! ✨ 🍰 ✨ 1 file left unchanged.
10. it's not possible to start a program like pip
11. close pyto, restart ipad
12. Now try "Run module (python -m)" 
13. first line on REPL: All done! ✨ 🍰 ✨ 1 file left unchanged.
14. it's not possible to start a program like pip

I have to reinstall pyto to run a module!
same with 2v3  (without: All done! ✨ 🍰 ✨ 1 file left unchanged.)

pyto version 11.0 (7)
Ipad Pro, ios 12.4
same issue on iPhone Xs, ios 12.4

**Comment by ColdGrub1384** [comment]
Thank you! That's now fixed
