### ISSUE TITLE
Module ui_constants tries to convert iOS version into float

### ISSUE THREAD

**Issue by Dutcho** [ColdGrub1384/Pyto#72]
While some iOS versions (e.g. `13.0`) have a single point, this isn’t necessarily always true (`12.4.1`, but in future `13.x.y`).
At present, this just provides the wrong error message (below `ValueError` instead of intended `ImportError("PytoUI requires iPadOS / iOS 13")`) to ban using Pyto `ui` on the latest official iOS version (guess we’ll have to be patient until 13 is released). After the first minor update of iOS 13, it'll render Pyto's `ui` useless on a (supported) iOS 13 version. So that will increase the severity of this bug.
Suggest using e.g. `int(str(...).split('.')[0])` instead of `float(str(...))`.

```
>>> import ui_constants
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "Pyto.app/Lib/ui_constants.py", line 15, in <module>
    if UIDevice is not None and float(str(UIDevice.currentDevice.systemVersion)) < 13:
ValueError: could not convert string to float: '12.4.1'
```

**Comment by cclauss** [comment]
`float(str(...).split(".")[:2]`

**Comment by ColdGrub1384** [comment]
Thank you!
