### ISSUE TITLE
Adding statsmodels

### ISSUE THREAD

**Issue by mulra02** [ColdGrub1384/Pyto#73]
Do you think it is possible to add statsmodels module? Since scipy is already implemented, it seemed likely that it could be added.

**Comment by cclauss** [comment]
Did you try adding https://pypi.org/project/statsmodels yourself?

**Comment by ColdGrub1384** [comment]
`statsmodels` isn't pure Python so it has to be embedded in the app. It should be possible.

**Comment by mulra02** [comment]
I think version 11.10 adds this module, thanks a lot!
