### ISSUE TITLE
Get location

### ISSUE THREAD

**Issue by GitContainer** [ColdGrub1384/Pyto#76]
Is there any module that can get the location information  on ios in Pyto?

**Comment by ColdGrub1384** [comment]
No. The 'On my iPhone / iPad > Pyto' folder is '~/Documents'

**Comment by cclauss** [comment]
Latitude / Longitude location

**Comment by ColdGrub1384** [comment]
Ah ok. No there isn't. There are APIs for that but I think it's not 100% accurate.

```python
import requests

def display_ip():
    """  Function To Print GeoIP Latitude & Longitude """
    ip_request = requests.get('https://get.geojs.io/v1/ip.json')
    my_ip = ip_request.json()['ip']
    geo_request = requests.get('https://get.geojs.io/v1/ip/geo/' +my_ip + '.json')
    geo_data = geo_request.json()
    print({'latitude': geo_data['latitude'], 'longitude': geo_data['longitude']})

if __name__ == '__main__':
    display_ip()
```

**Comment by Dutcho** [comment]
I bet OP meant from the device’s GPS, not from an IP address, which is far less than 100% accurate (especially when on mobile network)

**Comment by cclauss** [comment]
The IP method is problematic.   My internet provider puts me in the capitol of my region which is a 2+ hour drive from here.  The builtin GPS might be inaccurate but it will be MUCH better than the IP method.

**Comment by ColdGrub1384** [comment]
I added a `location` module
