### ISSUE TITLE
Include paramiko

### ISSUE THREAD

**Issue by goerz** [ColdGrub1384/Pyto#77]
Would it be possible to include paramiko as a 3rd party library? While paramiko itself is pure python, I don't think its crypto dependencies are. Trying to pip-install paramiko in Pyto appears to time out while trying to install `pynacl`.

**Comment by ColdGrub1384** [comment]
I will work on it. I will try to include `pynacl`, then installing `paramiko` wouldn’t be a problem.

**Comment by goerz** [comment]
Sounds good! There may be additional dependencies with extension modules, though

**Comment by ColdGrub1384** [comment]
I added `PyNaCl` but now I need to add more modules to make `paramiko` work.

**Comment by ColdGrub1384** [comment]
I just added `bcrypt` and `cryptography`. A bit late, sorry. `cryptography` was hard to make work.

**Comment by ColdGrub1384** [comment]
`paramiko` from PyPi will be usable on the next update.
