### ISSUE TITLE
ValueError on iOS 13.1.1 from version parsing

### ISSUE THREAD

**Issue by goerz** [ColdGrub1384/Pyto#79]
After updating to iOS13.1.1, running any script results in an exception:

~~~
Traceback (most recent call last):
...
  File "Pyto.app/Lib/pyto_ui.py", line 28, in <module>
    import ui_constants
  File "Pyto.app/Lib/ui_constants.py", line 15, in <module>
    if UIDevice is not None and float(str(UIDevice.currentDevice.systemVersion)) < 13:
ValueError: could not convert string to float: '13.1.1'
~~~
You'll probably want to use `pkg_resources.parse_version` or some other method from https://stackoverflow.com/questions/11887762

**Comment by ColdGrub1384** [comment]
Thank you! I will release an update as soon as possible.

**Comment by ColdGrub1384** [comment]
I just looked at code and I fixed this a long time ago. Do you have the latest version? Or maybe the app is caching the module but I don’t think so because it does not have right to write in the app bundle

**Comment by goerz** [comment]
I'm running the latest Testflight version [11.0 (18) Sep 12, 2019 at 23:39], according to the Information on the Settings screen

**Comment by goerz** [comment]
Ah, sorry.. The latest App Store version (which is newer than Testflight) works fine.

It might be good to always have the Testflight version to be at least as new as the App Store version.

**Comment by goerz** [comment]
Actually, the `notification_center` module still seems to have this problem, see the `Dice.py` example.

**Comment by ColdGrub1384** [comment]
Yes, a new update is available on the AppStore and soon on TestFlight.
