### ISSUE TITLE
Make documentation available online

### ISSUE THREAD

**Issue by goerz** [ColdGrub1384/Pyto#82]
The documentation viewer embedded in the app is rather limited. For example, it does not allow to search on the current page, which makes it difficult to navigate the pyto_ui API. Could you upload the documentation somewhere online, e.g. on `readthedocs.org`?

**Comment by ColdGrub1384** [comment]
I will try to upload in `readthedocs.org`

**Comment by ColdGrub1384** [comment]
It's now available in ReadTheDocs: https://pyto.readthedocs.io
