### ISSUE TITLE
Rich text labels

### ISSUE THREAD

**Issue by goerz** [ColdGrub1384/Pyto#83]
Is there any way to create a "rich text label", where some word in a longer text label is bold or italic?

**Comment by ColdGrub1384** [comment]
That’s not currently possible, but if you don’t need editing, there is `WebView` where you can load HTML.

**Comment by goerz** [comment]
No editing required. I’ll give it a try!

**Comment by ColdGrub1384** [comment]
I added `load_html(html)` method to `Label` and `TextView` for loading HTML
