### ISSUE TITLE
Module notification_center tries to convert iOS version into float

### ISSUE THREAD

**Issue by Dutcho** [ColdGrub1384/Pyto#85]
Like https://github.com/ColdGrub1384/Pyto/issues/72, but then for notification_center

Also, with iOS/iPadOS 13.1.2 out now, this actively limits usability
Might be worth the trouble to run a grep over the entire codenamen to unearth any other of such uses

**Comment by ColdGrub1384** [comment]
This is now fixed in the latest AppStore update and TestFlight build.
