### ISSUE TITLE
Does Pyto have official support channels ?

### ISSUE THREAD

**Issue by Brun0oO** [ColdGrub1384/Pyto#87]
... like forum, google group or discord/matrix/slack channel where users can share experiences, help themselves about Pyto.... It's strange to me to use the issue mechanism in this case...

**Comment by ColdGrub1384** [comment]
There is nothing for the moment but I could open a Discord.

**Comment by ColdGrub1384** [comment]
https://discord.gg/326ster. I will share it in Pyto's Settings also
