### ISSUE TITLE
Issue with code completion

### ISSUE THREAD

**Issue by 7points** [ColdGrub1384/Pyto#91]
In this example a comment after a class definition blocks the code completion after view. !
Deleting the comment will make code completion work.

```
import pyto_ui as ui

class test():
    ''' a comment here blocks code completion '''
    def __init__(self):
        pass

view = ui.View()
view.
ui.show_view(view, ui.PRESENTATION_MODE_SHEET)
```

**Comment by cclauss** [comment]
It is not a comment, it is a docstring but """docstring""" is preferred to '''docstring'''

**Comment by ColdGrub1384** [comment]
Using double quotes solves the problem

**Comment by 7points** [comment]
Oh yes, you are right. I sometimes used triple single quotes instead of triple double quotes for docstrings. Thanks!

**Comment by cclauss** [comment]
PEP8 to the rescue!
