### ISSUE TITLE
Add Tensorflow is perfect

### ISSUE THREAD

**Issue by goodclass** [ColdGrub1384/Pyto#96]
If you add this library, machine learning and deep learning will be connected.

Due to my limited skills in C compilation, I didn't do it.😅

**Comment by ColdGrub1384** [comment]
I will try to do it

**Comment by 7points** [comment]
Could this be a solution here?
https://www.tensorflow.org/lite/guide/build_ios

**Comment by goodclass** [comment]
This is the IOS lite version. It supports OC and swift development and requires Python excuse. It's not sure that Lite is the full version.
I am learning Tensorflow recently. I have enough knowledge about it first

**Comment by tmenguy** [comment]
+1

**Comment by cclauss** [comment]
TensorFlow still does not support Python 3.8.

**Comment by goodclass** [comment]
I don't need to compile tensorflow now. I already have pytorch. But now the mobile version is not stable and the compilation process is too complex. At that time, I will write down all the operation procedures
